# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointInPolygons
                                 A QGIS plugin
 The plugin shows point within a boundary
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-30
        copyright            : (C) 2024 by Samuel Njoka
        email                : bsc-com_09-20@unima.ac.mw
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointInPolygons class from file PointInPolygons.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Point_in_polygon_analyzer import PointInPolygons
    return PointInPolygons(iface)
